theme: jekyll-theme-architect
url: https://prateekraawat1.github.io
permalink: /blog/:year/:month/:day/:title
title: Lakshmi Narain College of Techonology
description: Website developed for 1st year students.
